/**
 * @file CityReport.h
 *
 * @author Charles B. Owen
 *
 * The city report is generated by the members of the city.
 * It is a collection of objects of type MemberReport.
 */

#pragma once

#include "GrayCode.h"
#include <memory>
#include <vector>

class City;
class MemberReport;

/**
 * The city report is generated by the members of the city.
 * It is a collection of objects of type MemberReport.
*/
class CityReport
{
private:
    /// The city this report is for
    City* mCity;

protected:
    /// Vector containing all city reports in Gray Code order
    std::vector<std::shared_ptr<MemberReport>> mReports;

    /// Indication that the collection is empty
    bool mNoReports = true;

    /// Last added location in the collection
    /// Only valid if mNoReports is false, so we initialize
    /// it with an arbitrary value.
    unsigned int mLast = 47;

public:
    explicit CityReport(City* city);

    void Add(std::shared_ptr<MemberReport> report);
};

